# This is needed for tox.ini!!
name: synospec
channels:
  - defaults
dependencies:
  - python>=3.10
  - IPython>=8.0
  - pip
  - numpy>=1.24
  - scipy>=1.10
  - matplotlib>=3.6
  - astropy>=6.0
  - extension-helpers>=0.1
  - pydl>=0.7
  - shapely>=2.0
  - pytest>=6.2
  - setuptools>=46.4

