# Largely copied from github.com/pypeit/PypeIt
name: CI Tests

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

env:
  SETUP_XVFB: True  # avoid issues if something tries to open a GUI window

jobs:
  ci-tests:
    name: Tox env ${{ matrix.python }}-${{ matrix.toxenv }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.7, 3.8, 3.9]
        toxenv: [test, test-alldeps-cov, test-astropydev, conda]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}
    - name: Upload coverage to codecov
      if: "contains(matrix.toxenv, '-cov')"
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV }}
        file: ./coverage.xml
        fail_ci_if_error: true

  os-tests:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # set this to false for now so windows failures don't prevent macos test from finishing
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        python: [3.7, 3.8, 3.9]
        toxenv: [test-alldeps]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}

  codestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python codestyle check
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pycodestyle
    - name: Check for runtime errors using pycodestyle
      run: |
        pycodestyle synospec --count --select=E9


